config/routes.rb
GerenciadorEspectros::Application.routes.draw do

  devise_for :admins do get '/admins/sign_out' => 'devise/sessions#destroy' end

  root to: "Atletas#index"

  resources :atletas do
    get 'inadimplentes', :on => :collection
    get 'em_dia', :on => :member
  end
end

# :on => :member
  # => atletas/:id/inadimplentes
# :on => :collection
  # => atletas/inadimplentes

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         #:registerable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :nome, :telefone, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/atleta.rb
#encoding: utf-8

class Atleta < ActiveRecord::Base

  before_save :padronizar_data

  attr_accessible :email, :foto, :nome, :ultimo_pagamento, :posicao, :telefone

  validates :nome, :email, presence: true
  # validate :atleta_ja_em_dia


  default_scope order('nome')

  protected

  def padronizar_data
    self.ultimo_pagamento = self.ultimo_pagamento.change(day: 1)
  end

  def self.inadimplentes
    where('ultimo_pagamento < ?', Time.now.change(day: 1).to_date)
  end

  protected

  # def atleta_ja_em_dia
  #   errors.add(:ultimo_pagamento, 'O atleta já está em dia') if self.ultimo_pagamento >= Time.now.to_date
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/atletas_controller.rb
#encoding: utf-8
class AtletasController < ApplicationController

  before_filter :authenticate_admin!, only: [:new, :edit, :update, :destroy]

  def index
    @atletas = Atleta.all
  end

  def show
    @atleta = Atleta.find(params[:id])
  end

  def new
    @atleta = Atleta.new
  end

  def create
    @atleta = Atleta.new(params[:atleta])

    if @atleta.save
      flash[:notice] = 'Atleta criado com sucesso.'
      redirect_to @atleta
    else
      flash[:error] = 'Não foi possível criar o atleta.'
      render 'new'
    end

  end

  def edit
    @atleta = Atleta.find(params[:id])
  end

  def update
    @atleta = Atleta.find(params[:id])
    @atleta.update_attributes(params[:atleta])

    if @atleta.save
      flash[:notice] = 'Atleta atualizado com sucesso.'
      redirect_to @atleta
    else
      flash[:error] = 'Não foi possível atualizar o atleta.'
      render 'edit'
    end

  end

  def destroy
    @atleta = Atleta.find(params[:id]).destroy
    flash[:notice] = 'Atleta deletado com sucesso.'
    redirect_to atletas_path
  end

  def inadimplentes
    @atletas_inadimplentes = Atleta.inadimplentes
  end

  def em_dia
    @atleta = Atleta.find(params[:id])
    unless @atleta.ultimo_pagamento > Time.now.to_date
      @atleta.update_attributes(:ultimo_pagamento => Time.now.to_date)

      redirect_to(:back, :notice => "Atleta #{@atleta.nome} está em dia.")
    end
  end
end

app/helpers/application_helper.rb
#encoding: utf-8
module ApplicationHelper

  def estilo_pagamento_pendente(atleta)
    return 'label label-important' if atleta.ultimo_pagamento.month < Time.now.month
    return 'label label-success' if atleta.ultimo_pagamento.month >= Time.now.month
  end

  def status_atleta(atleta)
    atleta.ultimo_pagamento.month >= Time.now.month
  end

  def inadimplente?(atleta)
    atleta.ultimo_pagamento < Time.now.to_date
  end

  def formata_data(data)
    data.strftime("%d/%m/%Y")
  end

  def meses_pagos_ou_atrasados(atleta)
    ((atleta.ultimo_pagamento - Time.now.to_date.change(day: 1))/30).to_i
  end


  def num_to_month(num_mes)
    case num_mes
      when 1 then return ultimo_mes = 'Janeiro'
      when 2 then return ultimo_mes = 'Fevereiro'
      when 3 then return ultimo_mes = 'Março'
      when 4 then return ultimo_mes = 'Abril'
      when 5 then return ultimo_mes = 'Maio'
      when 6 then return ultimo_mes = 'Junho'
      when 7 then return ultimo_mes = 'Julho'
      when 8 then return ultimo_mes = 'Agosto'
      when 9 then return ultimo_mes = 'Setembro'
      when 10 then return ultimo_mes = 'Outubro'
      when 11 then return ultimo_mes = 'Novembro'
      when 12 then return ultimo_mes = 'Dezembro'
    end
    #End case
  end
  #End num_to_month

end

app/views/atletas/_form.html.haml
#encoding: utf-8
= form_for(@atleta) do |f|
  - @atleta.errors.full_messages.each do |msg|
    %li
      = msg
  %div
    = f.label :nome
    = f.text_field :nome

  %div
    = f.label :email
    = f.text_field :email

  %div
    = f.label :posicao
    = f.text_field :posicao

  %div
    = f.label :telefone
    = f.text_field :telefone

  %div
    = f.label :foto
    = f.text_field :foto

  %div
    = f.label 'Mês do ultimo pagamento'
    = f.text_field :ultimo_pagamento

  = f.submit class: 'btn btn-primary'

app/views/atletas/edit.html.haml
%h1
  Editar atleta

= render partial: 'form'

app/views/atletas/inadimplentes.html.haml
#encoding: utf-8

.row
  .span3.well.well-small.pull-left
    %strong
      = 'Data atual: ' + Time.now.strftime("%d/%m/%Y")
      %p
        Total de atletas inadimplentes: #{Atleta.inadimplentes.count}

%h1
  Atletas inadimplentes

- unless @atletas_inadimplentes.empty?
  %ul.lista_atletas
    - @atletas_inadimplentes.each do |atleta|
      %li
        %div.atleta_small_pic
          = link_to image_tag(atleta.foto), atleta
        %div.atleta_info_container
          %p
            Nome:
            = link_to atleta.nome, atleta
          %p
            Email:
            = atleta.email
          %p
            Último pagamento:
            = formata_data(atleta.ultimo_pagamento)
          %p
            = 'Mensalidades atrasadas: ' if meses_pagos_ou_atrasados(atleta) < 0
            = 'Mensalidades adiantadas: ' if meses_pagos_ou_atrasados(atleta) > 0
            = 'Mensalidades quitadas: ' if meses_pagos_ou_atrasados(atleta) == 0
            = 'Mês atual.' if meses_pagos_ou_atrasados(atleta).abs == 0
            = meses_pagos_ou_atrasados(atleta).abs if meses_pagos_ou_atrasados(atleta).abs != 0
          %p
            Status:
            %span{class: estilo_pagamento_pendente(atleta)}
              = "Em dia" if status_atleta(atleta)
              = "Inadimplente" unless status_atleta(atleta)

          - if admin_signed_in?
            %p
              = link_to 'Em dia', em_dia_atleta_path(atleta), class: 'btn btn-mini btn-success'
              |
              = link_to 'Editar', edit_atleta_path(atleta), class: 'btn btn-mini'
              |
              = link_to 'Deletar', atleta_path(atleta), confirm: "Deseja deletar o atleta #{atleta.nome} ?", method: :delete, class: 'btn btn-mini btn-danger'

- else
  %i
    Não há atletas inadimplentes.

app/views/atletas/index.html.haml
#encoding: utf-8

.row
  .span3.well.well-small.pull-left
    %strong
      = 'Data atual: ' + Time.now.strftime("%d/%m/%Y")
      %p
        Total de atletas no sistema: #{Atleta.count}

%h1
  Atletas

- unless @atletas.empty?
  %ul.lista_atletas
    - @atletas.each do |atleta|
      %li
        %div.atleta_small_pic
          = link_to image_tag(atleta.foto), atleta
        %div.atleta_info_container
          %p
            Nome:
            = link_to atleta.nome, atleta
          %p
            Email:
            = atleta.email
          %p
            Último pagamento:
            = formata_data(atleta.ultimo_pagamento)
          %p
            = 'Mensalidades atrasadas: ' if meses_pagos_ou_atrasados(atleta) < 0
            = 'Mensalidades adiantadas: ' if meses_pagos_ou_atrasados(atleta) > 0
            = 'Mensalidades quitadas: ' if meses_pagos_ou_atrasados(atleta) == 0
            = 'Mês atual.' if meses_pagos_ou_atrasados(atleta).abs == 0
            = meses_pagos_ou_atrasados(atleta).abs if meses_pagos_ou_atrasados(atleta).abs != 0
          %p
            Status:
            %span{class: estilo_pagamento_pendente(atleta)}
              = "Em dia" if status_atleta(atleta)
              = "Inadimplente" unless status_atleta(atleta)
          %p
            - if admin_signed_in?
              - if inadimplente?(atleta)
                = link_to 'Em dia', em_dia_atleta_path(atleta), class: 'btn btn-mini btn-success'
                |
              = link_to 'Editar', edit_atleta_path(atleta), class: 'btn btn-mini'
              |
              = link_to 'Deletar', atleta_path(atleta), confirm: "Deseja deletar o atleta #{atleta.nome} ?", method: :delete, class: 'btn btn-mini btn-danger'

- else
  %i
    Não há atletas cadastrados ainda.

app/views/atletas/new.html.haml
%h1
  Novo atleta

= render partial: 'form'

app/views/atletas/show.html.haml
#encoding: utf-8
%h1
  = @atleta.nome
- if admin_signed_in?
  %p
    = link_to 'Editar', edit_atleta_path(@atleta), class: 'btn btn-mini btn-primary'

%p.atleta_pic
  = image_tag(@atleta.foto)
- if admin_signed_in? && inadimplente?(@atleta)
  = link_to 'Em dia', em_dia_atleta_path(@atleta), class: 'btn btn-mini btn-success'

%table.table.table-striped
  %thead
    %th
      Status
    %th
      Nome
    %th
      Email
    %th
      = 'Mensalidades atrasadas' if meses_pagos_ou_atrasados(@atleta) < 0
      = 'Mensalidades quitadas' if meses_pagos_ou_atrasados(@atleta) >= 0
    %th
      Mês do último pagamento

  %tbody
    %tr
      %td
        %span{class: estilo_pagamento_pendente(@atleta)}
          = "Em dia" if status_atleta(@atleta)
          = "Inadimplente" unless status_atleta(@atleta)
      %td
        = @atleta.nome
      %td
        = @atleta.email
      %td
        = 'Mês atual.' if meses_pagos_ou_atrasados(@atleta).abs == 0
        = pluralize(meses_pagos_ou_atrasados(@atleta).abs, 'mês', 'meses') if meses_pagos_ou_atrasados(@atleta).abs != 0
      %td
        = formata_data(@atleta.ultimo_pagamento)
        (#{num_to_month(@atleta.ultimo_pagamento.month)})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gerenciador Espectros</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="container">
  <% flash.each do |key, value| %>
  <div class="alert <%= key == :notice ? 'success' : key %> fadeout">
    <button type="button" class="close" data-dimiss="alert"> x
    </button>
    <span>
      <%= value.capitalize %>
    </span>
  </div>
  <% end %>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'Gerenciador Espectros', root_path, class: 'brand' %>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="divider-vertical"></li>
            <li>
              <%= link_to 'Home', root_path %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%= link_to "Atletas inadimplentes (#{Atleta.inadimplentes.count})", inadimplentes_atletas_path  %>
            </li>
            <li class="divider-vertical"></li>
            <% if admin_signed_in? %>
              <li>
                <%= link_to "Novo atleta", new_atleta_path %>
              </li>
            <% end %>
          </ul>
        </div>
        <ul class="nav pull-right">
          <% unless admin_signed_in?%>
            <li>
              <%= link_to 'Login', new_admin_session_path %>
            </li>
            <li>
              <%#= link_to 'Cadastro', new_admin_registration_path %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Logout', destroy_admin_session_path %>
            </li>
          <% end %>

        </ul>
      </div>
    </div>
  </div>

  <div class="row">
    <span class="span9">
    <%= yield %></div>
    </span>
    <span class="span3">
    </span>
  </div>


</body>
</html>